#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : glog
Version  : 0.4.0
Release  : 13
URL      : https://github.com/google/glog/archive/v0.4.0/glog-0.4.0.tar.gz
Source0  : https://github.com/google/glog/archive/v0.4.0/glog-0.4.0.tar.gz
Summary  : A C++ application logging library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: glog-lib = %{version}-%{release}
Requires: glog-license = %{version}-%{release}

%description
The %name package contains a library that implements application-level
logging.  This library provides logging APIs based on C++-style
streams and various helper macros.

%package dev
Summary: dev components for the glog package.
Group: Development
Requires: glog-lib = %{version}-%{release}
Provides: glog-devel = %{version}-%{release}
Requires: glog = %{version}-%{release}

%description dev
dev components for the glog package.


%package doc
Summary: doc components for the glog package.
Group: Documentation

%description doc
doc components for the glog package.


%package lib
Summary: lib components for the glog package.
Group: Libraries
Requires: glog-license = %{version}-%{release}

%description lib
lib components for the glog package.


%package license
Summary: license components for the glog package.
Group: Default

%description license
license components for the glog package.


%prep
%setup -q -n glog-0.4.0
cd %{_builddir}/glog-0.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578639618
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1578639618
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/glog
cp %{_builddir}/glog-0.4.0/COPYING %{buildroot}/usr/share/package-licenses/glog/43c9d4e201bf773d965455b593cd8a244d98564b
cp %{_builddir}/glog-0.4.0/packages/deb/copyright %{buildroot}/usr/share/package-licenses/glog/f423f91847eb01f6aa739cd4afd6991cfc51c03f
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/glog/log_severity.h
/usr/include/glog/logging.h
/usr/include/glog/raw_logging.h
/usr/include/glog/stl_logging.h
/usr/include/glog/vlog_is_on.h
/usr/lib64/libglog.so
/usr/lib64/pkgconfig/libglog.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/glog/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libglog.so.0
/usr/lib64/libglog.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/glog/43c9d4e201bf773d965455b593cd8a244d98564b
/usr/share/package-licenses/glog/f423f91847eb01f6aa739cd4afd6991cfc51c03f
